Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: rails

Metrics/LineLength:
  Max: 120
